For even more practice, clone https://github.com/rougier/numpy-100, make your own repo called

numpy-100, and then commit and push your solutions to your own repo.

In [1]:
import numpy as np

### a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
negatives = a < 0
positives = a > 0
evens = a % 2 == 0

### 1. How many negative numbers are there?

In [4]:
negs = negatives.sum()

### 2. How many positive numbers are there?

In [5]:
pos = positives.sum()

### 3. How many even positive numbers are there?

In [6]:
posandeven = (a > 0) & (a % 2 == 0)
posandeven.sum()

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [7]:
new_a = a + 3
positives_new = new_a > 0
print(positives_new)
positives_new.sum()

[ True  True  True  True  True  True  True  True  True False  True False]


10

### 5. If you squared each number, what would the new mean and standard deviation be?

In [8]:
a_sqrd = a**2
new_mean = a_sqrd.mean()
new_std_dev = a_sqrd.std()
print("New mean", new_mean)
print("New std dev", new_std_dev)

New mean 74.0
New std dev 144.0243035046516


### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.

In [9]:
mean = a.mean()
stda = a.std()
a_centered = a - mean
a_centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7. Calculate the z-score for each data point. Recall that the z-score is given by:

$$Z = \frac{x − μ}{σ}$$

In [10]:
z = a_centered / stda
print(z)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [11]:
points_and_zscores = list(zip(a_centered, z))
print(points_and_zscores)

[(1.0, 0.12403473458920847), (7.0, 0.8682431421244593), (9.0, 1.116312611302876), (20.0, 2.4806946917841692), (-5.0, -0.6201736729460423), (-4.0, -0.49613893835683387), (-3.0, -0.3721042037676254), (-3.0, -0.3721042037676254), (-3.0, -0.3721042037676254), (-9.0, -1.116312611302876), (0.0, 0.0), (-10.0, -1.2403473458920846)]


# Life w/o numpy to life with numpy

In [12]:
## Setup 1
# Use python's built in functionality/operators to determine the following:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
a = np.array(a)

#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the # numbers in above list

In [14]:
sum_of_a = a.sum()
sum_of_a

55

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the #
### numbers in the above list

In [15]:
min_of_a = a.min()

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the 
#### numbers in the above list

In [16]:
max_of_a = a.max()

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the #
#### numbers in the above list

In [17]:
mean_of_a = a.mean()

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying 
#### all the numbers in the above list together

In [18]:
product_of_a = a.prod()
product_of_a

3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number 
#### in a squared like [1, 4, 9, 16, 25...]

In [19]:
squares_of_a = a * a
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [20]:
odds_in_a = a % 2 == 1
odds_in_a

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [21]:
evens_in_a = a % 2 == 0
evens_in_a

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

## Setup 2: 
#### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, # a chessboard...

In [22]:
# Consider what it would take to find the sum, min, max, average, sum, 
# product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [23]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
b = np.array(b)
sum_of_b = b.sum()
sum_of_b

33

In [24]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = b.min()
min_of_b

3

In [25]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = b.max()

In [26]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = b.mean()

In [27]:
# Exercise 5 - refactor the following to use numpy for calculating the product of 
# all numbers multiplied together.
product_of_b = b.prod()
product_of_b

20160

In [28]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = b**2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [29]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = b % 2 == 1
odds_in_b

array([[ True, False,  True],
       [False,  True, False]])

In [30]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = b % 2 == 0

In [31]:
# Exercise 9 - print out the shape of the array b.
np.shape(b)

(2, 3)

In [32]:
# Exercise 10 - transpose the array b.
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [33]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.flatten()

array([3, 4, 5, 6, 7, 8])

In [34]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing 
# only 1 number (6 x 1)

In [35]:
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3
#### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [36]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

#### Exercise 1 - Find the min, max, sum, and product of c.

In [37]:
c = np.array(c)

In [38]:
c.min()

1

In [39]:
c.max()

9

In [40]:
c.sum()

45

In [41]:
c.prod()

362880

#### Exercise 2 - Determine the standard deviation of c.

In [42]:
c.std()

2.581988897471611

#### Exercise 3 - Determine the variance of c.

In [43]:
print(c.var())

6.666666666666667


#### Exercise 4 - Print out the shape of the array c

In [44]:
print(np.shape(c))

(3, 3)


#### Exercise 5 - Transpose c and print out transposed result.

In [45]:
print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### Exercise 6 - Get the dot product of the array c with c. 

In [46]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [47]:
sum_c_trans_c = (c * np.transpose(c)).sum()
print(sum_c_trans_c)

261


#### Exercise 8 - Write the code necessary to determine the product of c times c  transposed. Answer should be 131681894400.

In [48]:
product_c_trans_c = (c * np.transpose(c)).prod()
print(product_c_trans_c)

131681894400


## Setup 4

In [49]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

#### Exercise 1 - Find the sine of all the numbers in d

In [50]:
d = np.array(d)
print(np.sin(d))

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


#### Exercise 2 - Find the cosine of all the numbers in d

In [63]:
print(np.cos(d))

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


#### Exercise 3 - Find the tangent of all the numbers in d

In [52]:
print(np.tan(d))

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


#### Exercise 4 - Find all the negative numbers in d

In [68]:
print(d < 0)

[[False False False False False False]
 [False  True  True False False False]
 [False False  True False  True False]]


#### Exercise 5 - Find all the positive numbers in d

In [69]:
print(d > 0)

[[ True  True  True False  True  True]
 [ True False False  True  True False]
 [ True  True False  True False  True]]


#### Exercise 6 - Return an array of only the unique numbers in d.

In [55]:
unique_numbers = np.unique(d)
print(unique_numbers)

[-90 -45 -30   0  30  45  60  90 120 180 270]


#### Exercise 7 - Determine how many unique numbers there are in d.

In [57]:
unique_numbers.size

11

#### Exercise 8 - Print out the shape of d.

In [58]:
d.shape

(3, 6)

#### Exercise 9 - Transpose and then print out the shape of d.

In [59]:
d.transpose()

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

#### Exercise 10 - Reshape d into an array of 9 x 2

In [60]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])